# CMake generated Testfile for 
# Source directory: /data/data/com.termux/files/home/caesar-czr-real.old
# Build directory: /data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("CaesarConsensusTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_consensus_test")
set_tests_properties("CaesarConsensusTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;82;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarCoinbaseTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_coinbase_test")
set_tests_properties("CaesarCoinbaseTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;83;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarBlockBuilderTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_block_builder_test")
set_tests_properties("CaesarBlockBuilderTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;84;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarBlockTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_block_test")
set_tests_properties("CaesarBlockTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;85;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarMempoolTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_mempool_test")
set_tests_properties("CaesarMempoolTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;86;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarMempoolValidationTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_mempool_validation_test")
set_tests_properties("CaesarMempoolValidationTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;87;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarFoundationTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_foundation_test")
set_tests_properties("CaesarFoundationTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;88;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarProtocolDataTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_protocol_data_test")
set_tests_properties("CaesarProtocolDataTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;89;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarTransactionTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_transaction_test")
set_tests_properties("CaesarTransactionTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;98;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_difficulty_consensus_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_difficulty_consensus_test")
set_tests_properties("caesar_difficulty_consensus_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;151;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarUTXOTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_utxo_test")
set_tests_properties("CaesarUTXOTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;163;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarSerializationTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_serialization_test")
set_tests_properties("CaesarSerializationTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;164;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarKeyEncodingTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_key_encoding_test")
set_tests_properties("CaesarKeyEncodingTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;165;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarAddressTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_address_test")
set_tests_properties("CaesarAddressTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;166;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarOwnershipTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_ownership_test")
set_tests_properties("CaesarOwnershipTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;167;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarWalletTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_wallet_test")
set_tests_properties("CaesarWalletTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;168;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarTransactionSignatureTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_transaction_signature_test")
set_tests_properties("CaesarTransactionSignatureTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;169;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarSignatureTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_signature_test")
set_tests_properties("CaesarSignatureTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;170;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_difficulty_block_validation_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_difficulty_block_validation_test")
set_tests_properties("caesar_difficulty_block_validation_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;181;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_difficulty_blockchain_validation_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_difficulty_blockchain_validation_test")
set_tests_properties("caesar_difficulty_blockchain_validation_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;199;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarFullBlockConsensusTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_full_block_consensus_test")
set_tests_properties("CaesarFullBlockConsensusTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;216;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PProtocolTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_protocol_test")
set_tests_properties("CaesarP2PProtocolTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;235;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PFrameTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_frame_test")
set_tests_properties("CaesarP2PFrameTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;254;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PHelloTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_hello_test")
set_tests_properties("CaesarP2PHelloTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;264;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PPingTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_ping_test")
set_tests_properties("CaesarP2PPingTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;271;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PTcpTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_tcp_test")
set_tests_properties("CaesarP2PTcpTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;278;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PConnectionTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_connection_test")
set_tests_properties("CaesarP2PConnectionTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;285;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PPeerManagerTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_peer_manager_test")
set_tests_properties("CaesarP2PPeerManagerTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;292;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_server_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_server_test")
set_tests_properties("caesar_p2p_server_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;299;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_handshake_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_handshake_test")
set_tests_properties("caesar_p2p_handshake_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;305;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_server_handshake_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_server_handshake_test")
set_tests_properties("caesar_p2p_server_handshake_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;311;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_server_reject_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_server_reject_test")
set_tests_properties("caesar_p2p_server_reject_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;317;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_server_version_reject_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_server_version_reject_test")
set_tests_properties("caesar_p2p_server_version_reject_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;323;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarBlockchainStorageTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_blockchain_storage_test")
set_tests_properties("CaesarBlockchainStorageTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;338;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_frame_security_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_frame_security_test")
set_tests_properties("caesar_p2p_frame_security_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;358;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("caesar_p2p_connection_security_test" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_connection_security_test")
set_tests_properties("caesar_p2p_connection_security_test" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;378;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarNodeTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_node_test")
set_tests_properties("CaesarNodeTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;388;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarTwoNodeP2PTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_two_node_p2p_test")
set_tests_properties("CaesarTwoNodeP2PTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;400;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarBlockchainSyncTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_blockchain_sync_test")
set_tests_properties("CaesarBlockchainSyncTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;417;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PRelayHeadersValidationTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_relay_headers_validation_test")
set_tests_properties("CaesarP2PRelayHeadersValidationTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;434;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarP2PRelayDisconnectedBlockTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_p2p_relay_disconnected_block_test")
set_tests_properties("CaesarP2PRelayDisconnectedBlockTest" PROPERTIES  _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;451;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarCARRCoreTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_carr_core_test")
set_tests_properties("CaesarCARRCoreTest" PROPERTIES  ENVIRONMENT "CAESAR_CARR_TEST_ROOT=/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/carr-test-runtime" WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;470;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarCARRRuntimeTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_carr_runtime_test")
set_tests_properties("CaesarCARRRuntimeTest" PROPERTIES  ENVIRONMENT "CAESAR_CARR_RUNTIME_TEST_ROOT=/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/carr-runtime-test" WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;497;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarCARRSupervisorTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_carr_supervisor_test")
set_tests_properties("CaesarCARRSupervisorTest" PROPERTIES  WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;525;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarCARRCaesardIntegrationTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_carr_caesard_integration_test")
set_tests_properties("CaesarCARRCaesardIntegrationTest" PROPERTIES  ENVIRONMENT "CAESARD_EXECUTABLE=/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesard;CAESAR_CARR_CAESARD_TEST_ROOT=/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/carr-caesard-runtime" WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;550;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarFeePolicyTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_fee_policy_test")
set_tests_properties("CaesarFeePolicyTest" PROPERTIES  WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;572;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
add_test("CaesarEconomicsTest" "/data/data/com.termux/files/home/caesar-czr-real.old/build-upload-check/caesar_economics_test")
set_tests_properties("CaesarEconomicsTest" PROPERTIES  WORKING_DIRECTORY "/data/data/com.termux/files/home/caesar-czr-real.old" _BACKTRACE_TRIPLES "/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;592;add_test;/data/data/com.termux/files/home/caesar-czr-real.old/CMakeLists.txt;0;")
