plugins { id 'com.android.application' }

android {
    namespace 'com.caesarczr.wallet'
    compileSdk 34

    defaultConfig {
        applicationId "com.caesarczr.wallet"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }

    androidResources {
        noCompress 'caesar_web'
    }
}
